config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ranks#index'
  
  resources :ranks do
    resources :artists do
      #resource :comments
      # dont' want too many layers of nesting!
    end
  end
  
  resources :artists do
    resources :songs do
      #resource :comments
      # dont' want too many layers of nesting!
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :rank
  has_many :songs, dependent: :destroy
  validates :name, :genre, presence: true
  validates :name, length: { minimum: 1 }
end

app/models/rank.rb
class Rank < ApplicationRecord
  #The parent model
  validates :current_rank, :last_week, :total_weeks, presence: true
  validates :current_rank, :last_week, :total_weeks, numericality: { only_integer: true }
  has_many :artists, dependent: :destroy
  # has_one: :artist ??? because there can only be one artist for a given rank?
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :name, :duration, presence: true
  validates :duration, numericality: { only_integer: true }
  validates :name, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :destroy, :update]
  before_action :set_rank

  def index
    @artists = @rank.artists

  end

  def show
    @artist = Artist.find(params[:id])

  end

  def new
    @artist = @rank.artists.new
    render partial: "form"
  end

  def create
    @artist = @rank.artists.new(artist_params)
    if @artist.save
      redirect_to [@rank, @artist]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

def update
  @artist = Artist.find(params[:id])
  if  @artist.update(artist_params)
    redirect_to [@rank, @artist]
  else
    render :edit
  end
end

def destroy
  @artist.destroy
  redirect_to rank_artists_path(@rank)
end


private

def artist_params
  params.require(:artist).permit(:artist_name, :genre)
end

def set_artist
  @artist = Artist.find(params[:id])
end

def set_rank
  @rank = Rank.find(params[:rank_id])
end

end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_rank, only: [:show, :update, :edit, :destroy]

  
  def index
    @ranks = Rank.all 
    # render index.html.erb
  end

  def show
    # @rank = Rank.find(params[:id])
    # render show.html.erb
  end

  def new
    @rank = Rank.new
    # render new.html.erb
    render partial: 'form'
  end

  def edit
    # @rank = Rank.find(params[:id])
    # render edit.html.erb edit form
    render partial: 'form'
  end

  def create
    @rank = Rank.new(rank_params)
    if @rank.save
      redirect_to ranks_path
    else
      render :new
    end
  end

  def update
    # @rank = Rank.find(params[:id])
    if @rank.update(rank_params)
      redirect_to ranks_path
    else
      render :edit
    end
  end

  def destroy
    # @rank = Rank.find(params[:id])
    @rank.destroy
    redirect_to ranks_path
  end

  private 
    def rank_params
      params.require(:rank).permit(:current_rank, :last_week, :total_weeks)
    end

    def set_rank
      @rank = Rank.find(params[:id])
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  
  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
    render partial: "form"
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to [@artist, @song]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

def update
  if @song.update(song_params)
    redirect_to [@artist, @song]
  else
    render :edit
  end
end



private

  def song_params
    params.require(:song).permit(:name, :duration)
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? "Edit Artist" : "Create Artist" %></h1>
<hr />
<%= form_for [@rank, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :genre%>
  <%= f.text_field :genre, required: true %>
  
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1><%= @rank.current_rank %> Artists</h1>
<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.name, [@rank, artist] %>
    </li>
  <% end %>
</ul>
<%= link_to 'Create New Artist', new_rank_artist_path(@rank) %>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1><%= @rank.current_rank %>: <%= @artist.name %></h1>
<h2><%= @artist.genre %></h2>
<%= link_to 'Edit Artist', edit_rank_artist_path([@rank, @artist]) %>
<br/>
<%= link_to 'Delete Artist', [@rank, @artist], method: :delete %>
<br/>
<%= link_to 'Back to Artists', rank_artists_path(@rank) %>
<br/>
<%= link_to 'View Songs', artist_songs_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ranks/_form.html.erb
<h1><%= @rank.id ? 'Edit Rank' : 'Create Rank' %> </h1>
<%= form_for @rank do |f| %>
  <%= f.label :current_rank %>
  <%= f.text_field :current_rank, required: true %>

  <%= f.label :last_week %>
  <%= f.text_field :last_week, required: true %>
  
  <%= f.label :total_weeks %>
  <%= f.text_field :total_weeks, required: true %>

  <%= f.submit %>
<% end %>

app/views/ranks/edit.html.erb
<h1>Ranks#edit</h1>
<p>Find me in app/views/ranks/edit.html.erb</p>

app/views/ranks/index.html.erb
<h1> All Ranks </h1>
<ul>
  <% @ranks.each do |rank| %>
    <li>
      <%= link_to rank.current_rank, rank %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add New Rank', new_rank_path %>

app/views/ranks/new.html.erb
<h1>Ranks#new</h1>
<p>Find me in app/views/ranks/new.html.erb</p>

app/views/ranks/show.html.erb
<h1><%= @rank.current_rank %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View all Ranks', ranks_path %>
<br />
<%= link_to 'View Artists', rank_artists_path(@rank) %>
<br />
<%= link_to 'Edit Rank', edit_rank_path(@rank) %>
<br />
<%= link_to 'Delete Rank', @rank, method: :delete %>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit song' : 'Create Song' %> </h1>

<%= form_for @song do |f| %>
  # form helper for rails
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  # does front-end validation
  
  <%= f.submit %>
<% end %>

<h1><%= @song.id ? "Edit Artist" : "Create Artist" %></h1>
<hr />
<%= form_for [@rank, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :genre%>
  <%= f.text_field :genre, required: true %>
  
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song/h1>

<%= form_with(model: @rank, local: true, class: "ui form") do |f|%>
<div class = "field">
  <%= f.label :name%>
  <%= f.text_field :name, required: true %>
</div>

<div class = "field">
  <%= f.label :duration %>
  <%= f.text_field :duration, required: true %>
</div>

<%= f.text_field :duration, required: true %>
#  f.submit nil, class: 'ui green button' %>
  #ui green button from style library
<% end %>

# can copy into edit also
# t.string "name"
#     t.integer "duration"
#     t.bigint "artist_id",

app/views/songs/index.html.erb
<h1>All Songs</h1>
<% @songs.each do |song| %>
  <%= link_to song.name, [@artist, @song] %>
<% end %>

app/views/songs/new.html.erb
<h1>New Song/h1>

<%= form_with(model: @rank, local: true, class: "ui form") do |f|%>
<div class = "field">
  <%= f.label :name%>
  <%= f.text_field :name, required: true %>
</div>

<div class = "field">
  <%= f.label :duration %>
  <%= f.text_field :duration, required: true %>
</div>

<%= f.text_field :duration, required: true %>
#  f.submit nil, class: 'ui green button' %>
  #ui green button from style library
<% end %>

# can copy into edit also
# t.string "name"
#     t.integer "duration"
#     t.bigint "artist_id",

app/views/songs/show.html.erb
<h1><%= @artist.name %>: <%= @song.name %></h1>
<%= link_to 'Edit Song', edit_artist_song_path([@artist, @song]) %>
<br/>
<%= link_to 'Delete Song', [@artist, @song], method: :delete %>
<br/>
<%= link_to 'Back to Artists', rank_artists_path(@rank) %>